name: Docker Image CI
on:
<<<<<<< HEAD
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASS }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag mauricioca07/express-randomquotes:latest
      
      - name: Docker Push
        run: docker push mauricioca07/express-randomquotes
=======
push:
branches: [ Tutorial9 ]
pull_request:
branches: [ Tutorial9 ]
jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: docker login
env:
DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
DOCKER_PASS: ${{secrets.DOCKERHUB_PASS}}
run: |
docker login -u $DOCKER_USER -p $DOCKER_PASS
- name: Build the Docker image
run: docker build . --file Dockerfile --tag jkn707/express-randomquotes:latest
- name: Docker Push
run: docker push jkn707/express-randomquotes
>>>>>>> dffd95ad3f9977727d30ed9572c58926fa9016a0
